name: Test image build
on:
  push:
    branches-ignore:
      - main
    paths:
      - Dockerfile
jobs:
  test-build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Set up QEMU
        uses: docker/setup-qemu-action@1f40c72289eff860ee54a304f1438e3cff362e0a # v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4
      - name: Build docker image
        uses: docker/build-push-action@ef1fb9688fc3626d0fd5e462f502cbbdc6456feb
        with:
          context: .
          push: false
          platforms: linux/amd64
